blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/2025-LIKELION-HACKATHON-NIEUNDASEOT/backend
    about: Ask and answer questions with other members of the community.